### PR TITLE
Update BSB_lan.ino

### PR DESCRIPTION
**Pull request by dukess**
forced flushing

### CODE REVIEW

**Comment by dukess** [comment]
menu still hangs. I'm still investigating

**Comment by fredlcore** [comment]
Could it be that the browser- unless the connection is closed - expects s minimum amount of bytes before it starts displaying the received content? 
Maybe sending a few hundred of spaces after "Scanning for devices" will do the trick?

**Comment by dukess** [comment]
the browser tries to display the page during loading, AFAIK.
I tried to capture a packets between device and browser and saw 10 seconds pause (as you told):

BSB lan sent two packets
```
11	0.062003	192.168.67.5	192.168.3.42	TCP	954	80 → 53425 [PSH, ACK] Seq=1 Ack=523 Win=2048 Len=900 [TCP segment of a reassembled PDU]
12	0.070042	192.168.67.5	192.168.3.42	TCP	975	80 → 53425 [PSH, ACK] Seq=901 Ack=523 Win=2048 Len=921 [TCP segment of a reassembled PDU]
```
browser sent confirmation:
`13	0.070086	192.168.3.42	192.168.67.5	TCP	54	53425 → 80 [ACK] Seq=523 Ack=1822 Win=65260 Len=0`
...and bsb-lan hangs here for 10 seconds:
`14	10.145371	192.168.67.5	192.168.3.42	TCP	557	80 → 53425 [PSH, ACK] Seq=1822 Ack=523 Win=2048 Len=503 [TCP segment of a reassembled PDU]`

**Comment by dukess** [comment]
I'm dumb!

`            while (millis() - startquery < 10000) {`
ten seconds of delay!

**Comment by dukess** [comment]
Done!

**Comment by fredlcore** [comment]
Great! Thanks!

**Comment by dukess** [comment]
I have 3 unsupported parameters:

```
6300
053D1193 - (parameter not supported)
DC C2 00 0B 06 3D 05 11 93 F1 52
DC 80 42 0E 07 05 3D 11 93 00 00 00 2C B8

7846
053D0DA4 - (parameter not supported)
DC C2 00 0B 06 3D 05 0D A4 F1 F8
DC 80 42 0D 07 05 3D 0D A4 00 00 6F 6E

8336
053D0011 - UNIT_HOUR_TEXT (parameter not supported)
DC C2 00 0B 06 3D 05 00 11 70 DA
DC 80 42 10 07 05 3D 00 11 00 02 F2 30 08 57 A2
```

**Comment by fredlcore** [comment]
To include these,I need your device family and variant.

**Comment by dukess** [comment]
Sorry
6225;6226;6224;6220;6221;6227;6229;6231;6232;6233;6234;6235;6223;6236;6237;
123;231;LMS15.000A349;4.2;;5.5;24.0;908;0;10101;12421;0;20;180440042;00010000F0;

**Comment by fredlcore** [comment]
Thanks, I have included these now into _defs.h, but the strange thing is that for 7846, there already was an entry for DEV_123_ALL with the correct command ID, so it should not have reported this one for your machine...

**Comment by fredlcore** [comment]
Oops, sorry, my bad, I was looking at 7845, not 7846. Have added the missing one for 7846 now as well.

**Comment by fredlcore** [comment]
One more thing I realized: The IPWE function has a broken output, the columns seem to have been shifted one to the right. Could that be related to your changes or was this broken before (haven't had a look at it for quite some time)?

**Comment by fredlcore** [comment]
Ok, fixed it myself :)...

**Comment by fredlcore** [comment]
However, I just figured out that average parameters are no longer calculated (all zero, not only in IPWE). Were you working on these as well?

**Comment by fredlcore** [comment]
I just figured out that it seems to have to do with AvgValues_Old when reading from SD card or when it is not -9999 (i.e. after one day), couldn't test the latter. Also, average values in IPWE are integers only, not floats...

**Comment by fredlcore** [comment]
Fixed the float output...

**Comment by dukess** [comment]
Can i propose 
```
      char tmpbuf[10];
      _printFIXPOINT(tmpbuf, avgValues[i], 1);
      printFmtToWebClient(PSTR("<br></td><td>%s"), tmpbuf);
```
instead 
`      printFmtToWebClient(PSTR("<br></td><td>%.1f"), (avgValues[i]));
`
?
AFAIK floats not allowed for printf for AVR.

**Comment by fredlcore** [comment]
If it is really not working on AVR, we can of course change it that way, but shouldn't the compiler complain about the current code? At least mine does not when I compile for AVR (although I haven't tested it running).

**Comment by dukess** [comment]
You right! I tested it right now on Mega and it's working! It looks like my information is outdated. However, now we can make the code more compact.

изображение

**Pull request merged**
