### PR TITLE
www/languages.js autogeneration

### PR DESCRIPTION
**Pull request by dukess**
Generate list of languages into www/languages.js. For external interfaces

### CODE REVIEW

**Comment by fredlcore** [comment]
Thanks!

**Comment by fredlcore** [comment]
I have one small problem now: Whenever I run create_undefs.pl, the .gz files appear as "changed" files to be added to GitHub. However, without any changes to the actual language files, there shouldn't be any changes and gzip should (in theory) produce the same compressed file again, so that no change in the content would be detected. Do you know why this is the case and is there a way to fix this? Otherwise I'll have to deal with these changes everytime I routinely run create_undefs.pl.

**Comment by dukess** [comment]
The first thing I can suggest is to generate a file with the names and dates of changes to the language files (LANG_*.h). And every time you run the script will check for changes to the date. If the file date has not changed, the script skips the file.

**Comment by fredlcore** [comment]
Found it, the -N command line of gzip option was the problem.

**Comment by fredlcore** [comment]
It stores the filename and timestamp data in the gzip header. Hope deflating the gzip still works, but I couldn't think of why it shouldn't...

**Pull request merged**
