### PR TITLE
binary search in findLine(), _printFIXPOINT() in MQTT

### PR DESCRIPTION
**Pull request by dukess**
binary search in findLine(). It must be more faster than old search (11-18 iterations instead 1-129), _printFIXPOINT() in MQTT
small optimizations
add/replace some russian texts

### CODE REVIEW

**Comment by fredlcore** [comment]
Thanks, could you also fix one bug regarding HIDE_UNKNOWN: The first one is fixed already, it should have been "return" instead of "continue", but still no "error 7" parameters are printed out (in grey) as before. Somehow these "error telegrams" are filtered before they get to query_printHTML. Could you check that please? Thanks!

**Comment by dukess** [comment]
Tried to fix it. Unfortunately without testing because i in business trip.

**Comment by dukess** [comment]
@fredlcore Fixed and tested.

**Comment by fredlcore** [comment]
Thanks!

**Pull request merged**
