### PR TITLE
BME280 sensors support.

### PR DESCRIPTION
**Pull request by dukess**
Reduce number of DHT22 sensors to 20.
Fixed wrong unit for abs humidity.
BME sensors programs use numbers 20200-20299.
Using I2C bus.
Pins: SDA/SCL on Mega and SDA1/SCL1 on Due.
First sensor must have 0x76 address.
Pullup resistor(s) must be used on Due.

Compiled but NOT TESTED.

### CODE REVIEW

**Comment by 1coderookie** [comment]
Cool, thanks, will test it asap.
Up to me you could change the max amount of BME280 to 2, cuz afaik BME280 always come with 0x76-address and can only be changed to 0x77 if one changes something at the sensor hardware / pcb itself by cutting a contact and soldering another contact. So iirc it's not even possible to connect more than 2 of them to the I2C anyway (and I guess most people will stick with one anyway).

**Comment by fredlcore** [comment]
Thanks! But why the reduction to 20 DHT sensors (not that anyone will need these many anyways, but just out of curiousity)?

**Comment by dukess** [comment]
> Up to me you could change the max amount of BME280 to 2 (20200-20299 are 100!), cuz afaik BME280 always come with 0x76
For every sensor using 6 programs: ID, temp, humidity, Abs humidity, pressure, altitude. Other programs can be used for new sensors types in future. 

> But why the reduction to 20 DHT sensors (not that anyone will need these many anyways, but just out of curiousity)?

Reason is only one: for a more logical layout in the category. I could add the programs at the end, from 20900 to 20950, but then the sensors would go after the contents of the arrays

**Comment by fredlcore** [comment]
Ok, thanks!

**Comment by 1coderookie** [comment]
> > Up to me you could change the max amount of BME280 to 2 (20200-20299 are 100!), cuz afaik BME280 always come with 0x76
> 
> For every sensor using 6 programs: ID, temp, humidity, Abs humidity, pressure, altitude. Other programs can be used for new sensors types in future.
> 

Ah yes, sure - sorry, didn't think of that right now ;)

**Comment by fredlcore** [comment]
Due to another merge, there are now conflicts, could you check please?

**Comment by 1coderookie** [comment]
> Pullup resistor(s) must be used on Due.
> 
> Compiled but NOT TESTED.

Just tried - isn't it merged yet?
@dukess: What do you mean by "Pullup resistor(s) must be used on Due"? Ususally there's no need to add any pullups, you just have to connect the four pins..? Where/how should one add a pullup?

**Comment by fredlcore** [comment]
Merged just now

**Comment by dukess** [comment]
@1coderookie I have read on various websites that the second I2C bus requires external resistors. It is possible that this is erroneous information, but I can't check it, so I thought it would be better to write a warning.

**Comment by 1coderookie** [comment]
Ah ok, got it. At the 'usual' breakout boards there are already external pullups added, also a levelshifter etc., but you're right - sometimes it could be neccessary to add them if they aren't already existent on the board (there seem to be different boards available). Will make that note also in the manual, thanks, didn't think of that before ;)

**Comment by 1coderookie** [comment]
@dukess: Now there's the definement for BME280 in config.h which a) has to be activated and b) where one has to choose if one or two sensors are connected. Wouldn't it be good to also have that field within the webconfig like for DHT etc (but not for the pins of course, just for the amount of connected BMEs)? Maybe even something like 0 = deactivated, 1 = 1sensor, 2 = 2sensors?

**Comment by 1coderookie** [comment]
So, did a new test. Adjusted config.h, serial monitor says
```
15:38:43.464 -> Init BME280 sensor(s)...
15:38:43.464 -> Sensor with address 76 found
```
but no values presented within /K49 (doesn't appear, maybe you didn't add?) or /20200-20299 (just empty page).. :(

**Comment by 1coderookie** [comment]
There is an error(?)-message while compiling, but it doesn't seem to bother so far cuz flashing is possible. But maybe that could be a reason..?
```
In file included from /tmp/arduino_build_363932/sketch/src/BlueDot_BME280/BlueDot_BME280.h:9:0,
                 from /tmp/arduino_build_363932/sketch/src/BlueDot_BME280/BlueDot_BME280.cpp:10:
/home/db/.arduino15/packages/arduino/hardware/sam/1.6.12/libraries/Wire/src/Wire.h: In member function 'uint8_t BlueDot_BME280::readByte(byte)':
/home/db/.arduino15/packages/arduino/hardware/sam/1.6.12/libraries/Wire/src/Wire.h:50:10: note: candidate 1: uint8_t TwoWire::requestFrom(int, int)
  uint8_t requestFrom(int, int);
          ^
/home/db/.arduino15/packages/arduino/hardware/sam/1.6.12/libraries/Wire/src/Wire.h:47:10: note: candidate 2: uint8_t TwoWire::requestFrom(uint8_t, uint8_t)
  uint8_t requestFrom(uint8_t, uint8_t);
          ^
```

**Comment by fredlcore** [comment]
If it compiles fine, it's just a warning, and if it comes from a library (such as Wire.h) and not from BSB_lan_*.*, then it has _usually_ nothing to do with the BSB-LAN problem.

**Comment by dukess** [comment]
@1coderookie Thank you for testing!
I found a mistake: I mixed up < and >. Fixed. https://github.com/fredlcore/bsb_lan/pull/313

>Now there's the definement for BME280 in config.h which a) has to be activated and b) where one has to choose if one or two sensors are connected. Wouldn't it be good to also have that field within the webconfig like for DHT etc (but not for the pins of course, just for the amount of connected BMEs)? Maybe even something like 0 = deactivated, 1 = 1sensor, 2 = 2sensors?

It is harder: every sensor require a object and their quantity hard-coded at building. Of course, we can redo this code to be able to dynamically change the sensors quantity, but it will take up more space in memory. Can we postpone this until the next release? I would like to make another release with Mega support.

**Comment by 1coderookie** [comment]
Sweet!
Bildschirmfoto von 2021-01-27 06-06-45

About webconfig: No problem, so let's leave it in config.h - most users won't change the amount of sensors anyway.. ;)

**Comment by dukess** [comment]
Thank you for testing!

**Comment by 1coderookie** [comment]
Thank you for implementing! :)
Didn't test it with two BMEs though, but I guess that also works fine.. ;)

**Comment by 1coderookie** [comment]
New chapter in the manual: https://1coderookie.github.io/BSB-LPB-LAN_EN/chap12.html#1233-notes-on-bme280-sensors

**Pull request merged**
