### PR TITLE
Optimize images [ImgBot]

### PR DESCRIPTION
**Pull request by BudBundi**
I have [ImgBot] installed and it optimized the images in my fork, so I push them back to the orginal

### CODE REVIEW

**Comment by BudBundi** [comment]
For the standard config lossless, see documentation https://imgbot.net/docs/

**Comment by fredlcore** [comment]
The images have been updated, therefore it cannot be merged right away, can you please check?

**Comment by BudBundi** [comment]
I try to rebase it later, I'm relative new to git clients

**Comment by fredlcore** [comment]
Ok, I'll close this until we've found a solution, feel free to reopen it whenever you're ready!

**Pull request closed without merging**
