### PR TITLE
[CI] Try to compile with MQTT and MQTT JSON

### PR DESCRIPTION
**Pull request by fl42**
To spot a bug like #157 before a user notices it :)
CI is expected to fail until #161 is merged

### CODE REVIEW

**Comment by fredlcore** [comment]
I still have to fully understand the whole GitHub actions subject, but this looks reasonable to me. I have merged #161 now, but the checks here still fail. How can I run them again?

**Comment by fl42** [comment]
I just rebased my fork to your master branch, should work now

**Comment by fredlcore** [comment]
Yes, great, thanks!

**Comment by fredlcore** [comment]
I'm not sure if this is related to your fix, but I got a user who reported that when renaming BSB_lan_config.h.default to BSB_lan_config.h (instead of copying it to a new file and leaving BSB_lan_config.h.default untouched), the compiler breaks with an error. 
I think it should be possible to just rename the file (because that's what it says in the manual), but if that would render the tests useless, then we should change the manual (cc'ing @1coderookie here, just in case).

**Comment by fl42** [comment]
Hi @fredlcore,

Should not be related to the tests as I did not change anything to the code or how the config is managed.
On my side I'm able to compile using plateformio without BSB_lan_config.h.default.

The best would be to open an issue with the error message so we could investigate @1coderookie?

**Comment by fredlcore** [comment]
Not sure if I can get him to do that so quickly, but here's what he wrote in German:

Ein kleines Problem hatte ich. Die BSB_lan_config.h.default hatte ich entsprechend der Anleitung umbenannt. Damit lässt sich das Projekt aber nicht kompilieren, da der Link tests/config/BSB_lan_config_default.h dann auf die nicht mehr existierende Datei BSB_lan_config.h.default verweist. 

Since it mentions the tests folder,I assume it has nothing to do with the main code.
Even though most of us are not using the Arduino IDE, this is what 95% of ordinary users will be using, so we need to make sure it compiles there without errors...

**Comment by fl42** [comment]
Got it, sorry for the issue
Actually tests/config/BSB_lan_config_default.h is a symbolic link to BSB_lan_config_default.h
If BSB_lan_config_default.h is renamed, Arduino IDE fails because of the broken symlink (even if it does not need this symlink)
I'll open a PR to fix it, thanks for the head's up

**Comment by fredlcore** [comment]
Thanks!

**Comment by fredlcore** [comment]
Since now there is no symlink anymore, does this mean I have to manually update BSB_lan_config.h in both directories (main and tests)?

**Comment by fl42** [comment]
Yes,
In tests/config/ there are the configurations that will be used (successively) to build the code.

At the moment the CI makes sure that the project build with the default config, the config with MQTT without JSON, and the config with MQTT and JSON.

**Pull request merged**
