### PR TITLE
Chrismas edition.

### PR DESCRIPTION
**Pull request by dukess**
Fix: GET / return error 404 instead native web interface when WEBSERVER module enabled.
Fix for displaying VT_CUSTOM_ENUM and VT_CUSTOM_BIT enumerations.

New: module JSONCONFIG
New commands:
/JL - generate List of config options in JSON
/JW - read config options from JSON and apply new values

New: JSONCONFIG definition in _config.h.default added
New: Program 20006 can reset counters 20000-20005

Improvements: Code cleanup/optimization/rewrite
Improvements: /C output optimization
Improvements: /E now can display VT_BITS and VT_CUSTOM_BITS enums.
Improvements: Small piece of RU localization

### CODE REVIEW

**Comment by fredlcore** [comment]
Great, thanks a lot!
Two questions: /B0 will still work, but will be a shortcut to 20006?
And just for my understanding: Why are these lines no longer necessary?
```
              decodedTelegram.enumstr_len = get_cmdtbl_enumstr_len(i);
              decodedTelegram.enumstr = calc_enum_offset(get_cmdtbl_enumstr(i), decodedTelegram.enumstr_len);
```
They have been removed in several places, code looks cleaner, of course, but just so I understand it correctly where these are now set?

**Comment by dukess** [comment]
> /B0 will still work, but will be a shortcut to 20006?

Yep.  /B0 still work (direct reset values) but 20006 have other algoritm (user call set() for virtual program 20006 and handler reset values).

>              decodedTelegram.enumstr_len = get_cmdtbl_enumstr_len(i);
              decodedTelegram.enumstr = calc_enum_offset(get_cmdtbl_enumstr(i), decodedTelegram.enumstr_len);

These two strings was moved to loadPrognrElementsFromTable() function which calling every time at begin in printTelegram() and some other places.

**Comment by 1coderookie** [comment]
Cuz it's the "Christmas edition": Merry Christmas and already a happy and healthy new year! ;)

**Comment by fredlcore** [comment]
Thanks for the explanation, will merge now before I leave for Christmas :)... All the best to you two, too!

**Comment by dukess** [comment]
Merry Christmas Frederik, Ulf!

**Pull request merged**
