### PR TITLE
Handlers for applying settings on the fly

### PR DESCRIPTION
**Pull request by dukess**
CF_LOGCURRINTERVAL_TEXT now "Log interval, seconds"
Handlers added for applying settings on the fly or reboot where it need

Not tested on devices

### CODE REVIEW

**Comment by dukess** [comment]
Last for today

**Comment by fredlcore** [comment]
Thanks, but checks are not successful - can/should I still merge?

**Comment by fredlcore** [comment]
I'm sorry for asking this stupid questions, but what is the general procedure if the GitHub checks fail? Is this just a precaution or should I then wait with a merger until the checks are running fine?

**Comment by dukess** [comment]
>I'm sorry for asking this stupid questions, but what is the general procedure if the GitHub checks fail? Is this just a precaution or should I then wait with a merger until the checks are running fine?

If i understand, compiler on github is more strikly, because gcc from Arduino Studio allows some "triks" like late functions definitions and declarations. And... differences in local config and config on github allow catch some problems on the fly.

**Comment by dukess** [comment]
Give me one more minute

**Comment by dukess** [comment]
Ready.

**Pull request merged**
