### PR TITLE
reset for Due. NOT TESTED "in vivo"

### PR DESCRIPTION
**Pull request by dukess**

### CODE REVIEW

**Comment by fredlcore** [comment]
Thanks, will try!

**Comment by fredlcore** [comment]
Unfortunately, it does not work. Due hangs after performing this reset. I think I tried the solutions in this thread before and none of those seemed to have worked, but I don't know why. Maybe you can try with the real one once you have the Due?

**Comment by fredlcore** [comment]
Oh, and I checked the thread you were linking to, and at the end they actually mention
`  rstc_start_software_reset(RSTC);`
and not
`  rstc_set_external_reset(RSTC, 256);`
as you submitted. I tried with the first one and now it works!
Any reason why you went for the second one?

**Comment by dukess** [comment]
can you try rstc_start_software_reset(RSTC);
This is function from forum thread without restart ethernet shield.

**Comment by fredlcore** [comment]
Yes, that's the one I meant, that one worked. Didn't know that the other one would reset the Ethernet shield. However, it's not the Ethernet shield that is the problem because also when I have the Due on my serial monitor, it just hangs there after the reset command, no prior-to-ethernet debug messages etc.
But as long as the other command works, I think we're fine...

**Comment by dukess** [comment]
rstc_set_external_reset(RSTC, 256); must reset external devices too. It may need to select the duration value, because `RSTC->RSTC_MR = 0xA5000801; // Set RST pin to go low for 256 clock cycles on reset`
 0801 is not like 256

**Comment by fredlcore** [comment]
Ah, ok, so what value should I try? Longer or shorter?

**Comment by dukess** [comment]
Hmmm... 2048?

**Comment by fredlcore** [comment]
Tried 2049 (as per 0x0801), no luck...
Does this actually perform a reset or just set the time for the reset pin?

**Comment by fredlcore** [comment]
10 also doesn't work...

**Comment by dukess** [comment]
Found one example: 
https://cpp.hotexamples.com/ru/examples/-/-/rstc_set_external_reset/cpp-rstc_set_external_reset-function-examples.html
`rstc_set_external_reset(RSTC, 13);	/* (2^(13+1))/32768 */ `
delay is 0.5 sec here, so 256 is too big.

**Comment by fredlcore** [comment]
Using both lines and a value of 13 also does not work :(...

**Comment by fredlcore** [comment]
So far 
`rstc_start_software_reset(RSTC);`
is the only one that works...

**Comment by dukess** [comment]
Ok. We will use it until board arrive to me.

**Pull request merged**
