### PR TITLE
Bugfixes in JSON, speedup

### PR DESCRIPTION
**Pull request by dukess**
Bugfix: unknown JSON commands hanging the program;
Bugfix for JSON: wrong data type was returned with /JQ command when we got error 7.

Code changed:
Parameter searching in printTelegram() was "splitted" for two parts: 1. For defined parameter numbers - binary search; 2. For undefined parameter number (-1) - sequential search as before.
It will increase perfomance for QUERY and SET operations.

Code cleanup:
sprintf()->sprintf_P(), on advice of @loetmeister in https://github.com/fredlcore/bsb_lan/issues/102
client.print() -> bufferedprint();

### CODE REVIEW

**Comment by fredlcore** [comment]
Thanks!

**Comment by fredlcore** [comment]
Hi, I get the following errors when compiling on Due:
```
/Users/frederik/Documents/PlatformIO/Projects/BSB-LAN/src/BSB_lan.ino: In function 'void loadPrognrElementsFromTable(int)':
/Users/frederik/Documents/PlatformIO/Projects/BSB-LAN/src/BSB_lan.ino:1211:66: error: 'div_unit_len' was not declared in this scope
   memcpy(decodedTelegram.unit, optbl[decodedTelegram.type].unit, div_unit_len);
                                                                  ^~~~~~~~~~~~
/Users/frederik/Documents/PlatformIO/Projects/BSB-LAN/src/BSB_lan.ino:1211:66: note: suggested alternative: 'div_unit'
   memcpy(decodedTelegram.unit, optbl[decodedTelegram.type].unit, div_unit_len);
```

And this error repeats several times:

```
/Users/frederik/Documents/PlatformIO/Projects/BSB-LAN/src/BSB_lan.ino: In function 'void ds18b20()':
/Users/frederik/.platformio/packages/framework-arduino-sam/cores/arduino/avr/pgmspace.h:99:59: error: expected primary-expression before ')' token
 #define sprintf_P(s, f, ...) sprintf((s), (f), __VA_ARGS__)
/Users/frederik/Documents/PlatformIO/Projects/BSB-LAN/src/BSB_lan.ino:4278:16: note: in expansion of macro 'sprintf_P'
     outBufLen+=sprintf_P(outBuf+outBufLen,PSTR(" &deg;C\n</td></tr>\n"));
```

**Comment by dukess** [comment]
Moment. I fix it.

**Comment by dukess** [comment]
https://github.com/fredlcore/bsb_lan/pull/120

**Pull request merged**
