### PR TITLE
Bugfixes after revolution

### PR DESCRIPTION
**Pull request by dukess**
Bug fixes:
Board can't start with static IP now. Fixed.
UseEEPROM moved to config file. UseEEPROM = 0 can be used for fallback startup. Do not forget update config file.
Wrong info about logging and interval on config page.

Known issues:
Mega 2560 board: if program size more than ~245000 bytes you can got error "avrdude: verification error, first mismatch at byte 0x3c000"

WEBCONFIG module doesn't  work at this time on Mega:
C:\Users\User\AppData\Local\Temp\ccuOzsoN.s:115706: Error: value of 72118 too large for field of 2 bytes at 112281
C:\Users\User\AppData\Local\Temp\ccuOzsoN.s:115849: Error: value of 72118 too large for field of 2 bytes at 112468

### CODE REVIEW

**Comment by dukess** [comment]
Do not apply  now, please

**Comment by fredlcore** [comment]
Thans for the hint with the first byte mismatch error! I had this a few weeks back and thought that my Mega was broken, but if this is a "normal" error, then I know I can keep it :)...
Will wait for the merge until I get your "go ahead"...

**Comment by dukess** [comment]
This patch do something worse: now i can't get access through web and telnet. I need to take a walk and clear my head.

**Comment by fredlcore** [comment]
Ok, take your time!

**Comment by fredlcore** [comment]
Not sure if that helps, but it seems to be a certain time until the Arduino hangs: When I add output to the Serial port like this:
```
  Serial.println(1);
  Serial.println(2);
  server->begin();
  Serial.println(3);
  Serial.println(4);
```
It prints the "1" and _sometimes_ the "2", but that's it. Even when I put the number output further down in the code. Once it gets to the 1-Wire initialization, it's over and not even the "1" gets printed anymore. Very strange.

**Comment by fredlcore** [comment]
I have tried copying the function calls in Ethernet.begin from the (mac) to the (mac, ip, dns, gateway, subnet) function, and if I do a 1:1 copy, it works, but if I set the fixed IP hard-coded into the function, it somehow always gives me back 255.255.255.255. But it works. Maybe it would be worthwhile to investigate further what the difference is with the DHCP and the fixed IP begin()-functions?

**Comment by dukess** [comment]
Once idea i have: one (or more variables) will overwrite data of other objects.
Now i try build and run source from different times.

Revolution is very bloody.

**Comment by dukess** [comment]
I think to write small sketch with network testing because last more or less stable version was version before moving parameters from definitions to variables.

**Comment by fredlcore** [comment]
> Revolution is very bloody.

:)

**Comment by dukess** [comment]
I want to try one more time.

**Comment by fredlcore** [comment]
Means I should merge or not (yet)?

**Comment by dukess** [comment]
Short manual:
Add byte UseEEPROM = 1; in config
Enable 
#define CONFIG_IN_EEPROM
#define WEBCONFIG

Flash program

Start.
Call /C program, change config, save changes.
For store settings in EEPROM call /CS

**Comment by dukess** [comment]
You can merge

**Comment by fredlcore** [comment]
Great, fixed IP works, wonderful!
Did you find out what the problem was?

**Comment by dukess** [comment]
First problem: declared too small array for options table.
Second: deleted non-exist MQTTClient object (by fact - erased RAM in random addreses).

The main reason is an excessive passion for optimization %)

**Comment by fredlcore** [comment]
Ok :)...
I found a few more bugs, unfortunately for PPS, so we both will have to do the debugging:
When running in PPS mode, the on and off times have been read from EEPROM before already. Now I get strange time slots , they're all 42:30 hours, which means that a value of 0xFF is being read from EEPROM. It should somehow be made sure that this part of the EEPROM is zeroed out upon first start (or maybe easier: whenever there is a value higher than 144/0x90.
Also, the value for the QAA model to be sent for PPS telegram type 0x38 is not taken from the variable QAA_TYPE (which would be either 0x53 or 0x52), but it's also 0xFF.
I'll try to fix the latter now because otherwise PPS won't work at all because the heater needs to see the QAA type value before it sends or accepts data...

**Comment by fredlcore** [comment]
Ok, everything's fine once the EEPROM is overwritten with zeroes :). So a /JE should be issued on a fresh board. Do you think it would be feasible to check if the EEPROM has ever been zeroed-out? For example by looking for 0xFF in various places and then zero out the EEPROM?

**Comment by fredlcore** [comment]
...and the web-configuration is awesome!!!

**Comment by dukess** [comment]
Thank you for testing!

The problem with the bus is that I read the entire array. But, as I understand it, we need to read only part of the elements, the rest are used in the current work and should not be saved between sessions.

**Pull request merged**
